### ISSUE TITLE
The catalog service is not loading and so the products page is throwing an error

### ISSUE THREAD

**Issue by justinfraz** [abpframework/eShopOnAbp#189]
Hello!

In the Tye dashboard, all the other services are loading fine except for the catalog service.  It is throwing an error like so:

This site can’t be reachedlocalhost refused to connect.
Try:

**Checking the connection
[Checking the proxy and the firewall](chrome-error://chromewebdata/#buttons)
ERR_CONNECTION_REFUSED**

Is there a firewall configuration that I should implement?

As a result of the catalog service being down, the Products page is throwing an error like so:

**An error has occurred!
Http failure response for https://localhost:44354/api/catalog/product/paged: 0 Unknown Error**

Best Regards,

Justin

**Comment by jflaga** [comment]
Please check the logs of the Catalog microservice, then paste here the error you see in there.

**Comment by justinfraz** [comment]
Could you please tell me the location where I can check the logs?

**Comment by jflaga** [comment]
The logs for Catalog microservice is in `\eShopOnAbp\services\catalog\src\EShopOnAbp.CatalogService.HttpApi.Host\Logs\logs.txt`

**Comment by justinfraz** [comment]
The log file is quite long.  Is there an email address that I could mail it to?

**Comment by justinfraz** [comment]
When tried to run run-tye.ps1, these are the error messages that I got in the terminal console:

[09:16:19 ERR] watch: identity-service_94fa30cc-4 process exited with exit code 1
[09:16:19 WRN] Waiting for a file to change before restarting dotnet...
[09:16:22 INF] Event pipe collection completed for payment-service_337e8d78-a on process id 20408
[09:16:22 INF] payment-service_337e8d78-a process exited with exit code 1
[09:16:22 ERR] watch: payment-service_337e8d78-a process exited with exit code 1
[09:16:22 WRN] Waiting for a file to change before restarting dotnet...
[09:16:23 INF] Event pipe collection completed for ordering-service_28a4b1d3-9 on process id 15968
[09:16:23 INF] ordering-service_28a4b1d3-9 process exited with exit code 1
[09:16:24 ERR] watch: ordering-service_28a4b1d3-9 process exited with exit code 1
[09:16:24 WRN] Waiting for a file to change before restarting dotnet...
[09:16:31 INF] Event pipe collection completed for basket-service_839a6d2f-b on process id 25072
[09:16:31 INF] basket-service_839a6d2f-b process exited with exit code 1
[09:16:31 ERR] watch: basket-service_839a6d2f-b process exited with exit code 1
[09:16:31 WRN] Waiting for a file to change before restarting dotnet...
[09:16:33 INF] Event pipe collection completed for cmskit-service_b15f70b6-2 on process id 19392
[09:16:33 INF] cmskit-service_b15f70b6-2 process exited with exit code 1
[09:16:33 ERR] watch: cmskit-service_b15f70b6-2 process exited with exit code 1
[09:16:33 WRN] Waiting for a file to change before restarting dotnet...
[09:16:34 INF] Event pipe collection completed for public-web_0a06eb9f-b on process id 15064
[09:16:34 INF] public-web_0a06eb9f-b process exited with exit code 1
[09:16:34 ERR] watch: public-web_0a06eb9f-b process exited with exit code 1
[09:16:34 WRN] Waiting for a file to change before restarting dotnet...
[09:16:36 INF] Event pipe collection completed for administration-service_85f65dac-7 on process id 20340
[09:16:36 INF] administration-service_85f65dac-7 process exited with exit code 1
[09:16:36 ERR] watch: administration-service_85f65dac-7 process exited with exit code 1
[09:16:36 WRN] Waiting for a file to change before restarting dotnet...
[09:16:41 INF] Event pipe collection completed for catalog-service_06dd6ca3-d on process id 4068
[09:16:41 INF] catalog-service_06dd6ca3-d process exited with exit code 1
[09:16:41 ERR] watch: catalog-service_06dd6ca3-d process exited with exit code 1
[09:16:41 WRN] Waiting for a file to change before restarting dotnet...

I confirm that Docker Desktop is running.

**Comment by justinfraz** [comment]
The PublicWeb site is loading fine but when I proceed to complete the payment using the home or work addresses, demo card or paypal, I'm getting the following exception:

Volo.Abp.Http.Client.AbpRemoteCallException: Unauthorized
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.ThrowExceptionForResponseAsync(HttpResponseMessage response)
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.RequestAsync(ClientProxyRequestContext requestContext)
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.RequestAsync[T](ClientProxyRequestContext requestContext)
   at Volo.Abp.Http.Client.ClientProxying.ClientProxyBase`1.RequestAsync[T](String methodName, ClientProxyRequestTypeValue arguments)
   at EShopOnAbp.OrderingService.Orders.ClientProxies.OrderClientProxy.CreateAsync(OrderCreateDto input) in C:\Users\jstnf\Downloads\ABPeShop\services\ordering\src\EShopOnAbp.OrderingService.HttpApi.Client\ClientProxies\OrderClientProxy.Generated.cs:line 85
   at EShopOnAbp.PublicWeb.Pages.PaymentModel.OnPostAsync(PaymentPageViewModel model) in C:\Users\jstnf\Downloads\ABPeShop\apps\public-web\src\EShopOnAbp.PublicWeb\Pages\Payment.cshtml.cs:line 59
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Convert[T](Object taskAsObject)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.ExecutorFactory.GenericTaskHandlerMethod.Execute(Object receiver, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeHandlerMethodAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeNextPageFilterAsync()
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Rethrow(PageHandlerExecutedContext context)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.RazorPages.Infrastructure.PageActionInvoker.InvokeInnerFilterAsync()
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextExceptionFilterAsync>g__Awaited|26_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ExceptionContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeNextResourceFilter>g__Awaited|25_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Rethrow(ResourceExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeFilterPipelineAsync>g__Awaited|20_0(ResourceInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ResourceInvoker.<InvokeAsync>g__Logged|17_1(ResourceInvoker invoker)
   at Microsoft.AspNetCore.Routing.EndpointMiddleware.<Invoke>g__AwaitRequestTask|6_0(Endpoint endpoint, Task requestTask, ILogger logger)
   at EShopOnAbp.PublicWeb.AnonymousUser.AnonymousUserMiddleware.InvokeAsync(HttpContext context) in C:\Users\jstnf\Downloads\ABPeShop\apps\public-web\src\EShopOnAbp.PublicWeb\AnonymousUser\AnonymousUserMiddleware.cs:line 35
   at Microsoft.AspNetCore.Authorization.AuthorizationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Serilog.AbpSerilogMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Authentication.AuthenticationMiddleware.Invoke(HttpContext context)
   at Volo.Abp.AspNetCore.Tracing.AbpCorrelationIdMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Localization.RequestLocalizationMiddleware.Invoke(HttpContext context)
   at Microsoft.AspNetCore.RequestLocalization.AbpRequestLocalizationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next)
   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass6_1.<<UseMiddlewareInterface>b__1>d.MoveNext()
--- End of stack trace from previous location ---
   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddlewareImpl.Invoke(HttpContext context)

**Comment by jflaga** [comment]
Hi @justinfraz , you _might_ find the more specific error if you look at the logs in the Payment microservice: `\eShopOnAbp\services\payment\src\EShopOnAbp.PaymentService.HttpApi.Host\Logs\logs.txt`

Scroll to the bottommost messages, then look for the date and time which matches with the date-time when the error occurred. The error message looks similar to this (with **[ERR]**

```
...
2023-05-08 03:08:20.453 +08:00 [ERR] ...
...
```

Paste the error message here.

If you see two error messages which looks different, paste the two messages here.

An example error message looks like this:

```
2023-05-08 03:34:09.256 +08:00 [ERR] 42P01: relation "AbpPermissionGroups" does not exist

POSITION: 69
Npgsql.PostgresException (0x80004005): 42P01: relation "AbpPermissionGroups" does not exist

POSITION: 69
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|222_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode dataRowLoadingMode, Boolean readingNotifications, Boolean isReadingPrependedMessage)
   ...
```

or like this:

```
2023-05-04 20:30:21.209 +08:00 [ERR] An exception occurred while iterating over the results of a query for context type 'EShopOnAbp.AdministrationService.EntityFrameworkCore.AdministrationServiceDbContext'.
Npgsql.PostgresException (0x80004005): 42P01: relation "AbpPermissionGroups" does not exist

POSITION: 69
   at Npgsql.Internal.NpgsqlConnector.<ReadMessage>g__ReadMessageLong|222_0(NpgsqlConnector connector, Boolean async, DataRowLoadingMode 
   ...
```

**Comment by justinfraz** [comment]
Here are pretty much the errors of the type that you described above that I have located in the log file:

2023-08-27 18:24:05.963 +10:00 [ERR] ---------- Exception Data ----------
Severity = FATAL
InvariantSeverity = FATAL
SqlState = 3D000
MessageText = database "EShopOnAbp_Administration" does not exist
File = postinit.c
Line = 885
Routine = InitPostgres

2023-09-06 11:36:27.348 +10:00 [ERR] ---------- Exception Data ----------
Severity = FATAL
InvariantSeverity = FATAL
SqlState = 3D000
MessageText = database "EShopOnAbp_Administration" does not exist
File = postinit.c
Line = 885
Routine = InitPostgres

2023-09-06 16:44:24.502 +10:00 [ERR] ---------- Exception Data ----------
Severity = FATAL
InvariantSeverity = FATAL
SqlState = 3D000
MessageText = database "EShopOnAbp_Administration" does not exist
File = postinit.c
Line = 885
Routine = InitPostgres

2023-09-06 16:44:44.551 +10:00 [ERR] ---------- Exception Data ----------
Severity = FATAL
InvariantSeverity = FATAL
SqlState = 3D000
MessageText = database "EShopOnAbp_Administration" does not exist
File = postinit.c
Line = 885
Routine = InitPostgres

2023-09-13 09:58:13.130 +10:00 [ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "An internal error occurred during your request!",
  "details": null,
  "data": {},
  "validationErrors": null
}

**Comment by justinfraz** [comment]
Thank you very much @[gterdem](https://github.com/gterdem) for helping me resolve this issue.
