### ISSUE TITLE
Payment returns 500 on production

### ISSUE THREAD

**Issue by gterdem** [abpframework/eShopOnAbp#193]
Currently payment can not be completed and returns 500 on https://www.eshoponabp.com/

**Comment by skoc10** [comment]
Error Logs of Payment Service

`[16:19:13 ERR] ---------- RemoteServiceErrorInfo ----------
{
  "code": null,
  "message": "An internal error occurred during your request!",
  "details": null,
  "data": {},
  "validationErrors": null
}

[16:19:13 ERR] Nullable object must have a value.
System.InvalidOperationException: Nullable object must have a value.
   at EShopOnAbp.OrderingService.Orders.OrderAppService.GetMyOrdersAsync(GetMyOrdersInput input) in /src/services/ordering/src/EShopOnAbp.OrderingService.Application/Orders/OrderAppService.cs:line 46
   at lambda_method1166(Closure , Object )
   at Microsoft.AspNetCore.Mvc.Infrastructure.ActionMethodExecutor.AwaitableObjectResultExecutor.Execute(IActionResultTypeMapper mapper, ObjectMethodExecutor executor, Object controller, Object[] arguments)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeActionMethodAsync>g__Awaited|12_0(ControllerActionInvoker invoker, ValueTask`1 actionResultValueTask)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.<InvokeNextActionFilterAsync>g__Awaited|10_0(ControllerActionInvoker invoker, Task lastTask, State next, Scope scope, Object state, Boolean isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Rethrow(ActionExecutedContextSealed context)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.Next(State& next, Scope& scope, Object& state, Boolean& isCompleted)
   at Microsoft.AspNetCore.Mvc.Infrastructure.ControllerActionInvoker.InvokeInnerFilterAsync()`
