### ISSUE TITLE
.\run-tye.ps1

### ISSUE THREAD

**Issue by KerimNar** [abpframework/eShopOnAbp#259]
[20:34:00 INF] keycloak-seeder_b7eb207a-f process exited with exit code -532462766
[20:34:00 ERR] watch: keycloak-seeder_b7eb207a-f process exited with exit code -532462766
[20:34:00 WRN] Waiting for a file to change before restarting dotnet...
[20:34:35 INF] Event pipe collection completed for identity-service_2de8e2f4-d on process id 31336
[20:34:35 INF] identity-service_2de8e2f4-d process exited with exit code 1
[20:34:35 ERR] watch: identity-service_2de8e2f4-d process exited with exit code 1
[20:34:35 WRN] Waiting for a file to change before restarting dotnet...
[20:35:42 INF] Event pipe collection completed for catalog-service_d771e075-0 on process id 56776
[20:35:42 INF] catalog-service_d771e075-0 process exited with exit code 1
[20:35:42 ERR] watch: catalog-service_d771e075-0 process exited with exit code 1

**Comment by KerimNar** [comment]
**Tye Dashboard:**

EShopOnAbp.Keycloak.DbMigrator\EShopOnAbp.Keycloak.DbMigrator.csproj | none | 0/1

**log:**
[keycloak-seeder_0abd99d1-d]: Unhandled exception. Flurl.Http.FlurlHttpException: Call failed. No connection could be made because the target machine actively refused it. (localhost:8080) POST http://localhost:8080/realms/master/protocol/openid-connect/token
[keycloak-seeder_0abd99d1-d]: ---> System.Net.Http.HttpRequestException: No connection could be made because the target machine actively refused it. (localhost:8080)
[keycloak-seeder_0abd99d1-d]: ---> System.Net.Sockets.SocketException (10061): No connection could be made because the target machine actively refused it.
[keycloak-seeder_0abd99d1-d]: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.ThrowException(SocketError error, CancellationToken cancellationToken)
[keycloak-seeder_0abd99d1-d]: at System.Net.Sockets.Socket.AwaitableSocketAsyncEventArgs.System.Threading.Tasks.Sources.IValueTaskSource.GetResult(Int16 token)
[keycloak-seeder_0abd99d1-d]: at System.Net.Sockets.Socket.<ConnectAsync>g__WaitForConnectWithCancellation|285_0(AwaitableSocketAsyncEventArgs saea, ValueTask connectTask, CancellationToken cancellationToken)
[keycloak-seeder_0abd99d1-d]: at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
[keycloak-seeder_0abd99d1-d]: --- End of inner exception stack trace ---
[keycloak-seeder_0abd99d1-d]: at System.Net.Http.HttpConnectionPool.ConnectToTcpHostAsync(String host, Int32 port, HttpRequestMessage initialRequest, Boolean async, CancellationToken cancellationToken)
[keycloak-seeder_0abd99d1-d]: at System.Net.Http.HttpConnectionPool.ConnectAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[keycloak-seeder_0abd99d1-d]: at System.Net.Http.HttpConnectionPool.CreateHttp11ConnectionAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[keycloak-seeder_0abd99d1-d]: at System.Net.Http.HttpConnectionPool.AddHttp11ConnectionAsync(QueueItem queueItem)
[keycloak-seeder_0abd99d1-d]: at System.Threading.Tasks.TaskCompletionSourceWithCancellation`1.WaitWithCancellationAsync(CancellationToken cancellationToken)
[keycloak-seeder_0abd99d1-d]: at System.Net.Http.HttpConnectionPool.SendWithVersionDetectionAndRetryAsync(HttpRequestMessage request, Boolean async, Boolean doRequestAuth, CancellationToken cancellationToken)
[keycloak-seeder_0abd99d1-d]: at System.Net.Http.DiagnosticsHandler.SendAsyncCore(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[keycloak-seeder_0abd99d1-d]: at System.Net.Http.RedirectHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[keycloak-seeder_0abd99d1-d]: at System.Net.Http.DecompressionHandler.SendAsync(HttpRequestMessage request, Boolean async, CancellationToken cancellationToken)
[keycloak-seeder_0abd99d1-d]: at System.Net.Http.HttpClient.<SendAsync>g__Core|83_0(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationTokenSource cts, Boolean disposeCts, CancellationTokenSource pendingRequestsCts, CancellationToken originalCancellationToken)
[keycloak-seeder_0abd99d1-d]: at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
[keycloak-seeder_0abd99d1-d]: --- End of inner exception stack trace ---
[keycloak-seeder_0abd99d1-d]: at Flurl.Http.FlurlRequest.HandleExceptionAsync(HttpCall call, Exception ex, CancellationToken token)
[keycloak-seeder_0abd99d1-d]: at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
[keycloak-seeder_0abd99d1-d]: at Flurl.Http.FlurlRequest.SendAsync(HttpMethod verb, HttpContent content, CancellationToken cancellationToken, HttpCompletionOption completionOption)
[keycloak-seeder_0abd99d1-d]: at Flurl.Http.HttpResponseMessageExtensions.ReceiveJson[T](Task`1 response)
[keycloak-seeder_0abd99d1-d]: at Flurl.Http.HttpResponseMessageExtensions.ReceiveJson(Task`1 response)
[keycloak-seeder_0abd99d1-d]: at Keycloak.Net.Common.Extensions.FlurlRequestExtensions.GetAccessTokenAsync(String url, String realm, String userName, String password, KeycloakOptions options)
[keycloak-seeder_0abd99d1-d]: at Keycloak.Net.Common.Extensions.FlurlRequestExtensions.GetAccessToken(String url, String realm, String userName, String password, KeycloakOptions options)
[keycloak-seeder_0abd99d1-d]: at Keycloak.Net.Common.Extensions.FlurlRequestExtensions.WithAuthentication(IFlurlRequest request, Func`1 getToken, String url, String realm, String userName, String password, String clientSecret, KeycloakOptions options)
[keycloak-seeder_0abd99d1-d]: at Keycloak.Net.KeycloakClient.GetBaseUrl(String authenticationRealm)
[keycloak-seeder_0abd99d1-d]: at Keycloak.Net.KeycloakClient.GetRealmAsync(String realm, CancellationToken cancellationToken)
[keycloak-seeder_0abd99d1-d]: at EShopOnAbp.DbMigrator.KeyCloakDataSeeder.UpdateRealmSettingsAsync() in C:\Users\kerim\source\repos\abp\eShopOnAbp\shared\EShopOnAbp.Keycloak.DbMigrator\KeycloakDataSeeder.cs:line 49
[keycloak-seeder_0abd99d1-d]: at EShopOnAbp.DbMigrator.KeyCloakDataSeeder.SeedAsync(DataSeedContext context) in C:\Users\kerim\source\repos\abp\eShopOnAbp\shared\EShopOnAbp.Keycloak.DbMigrator\KeycloakDataSeeder.cs:line 40
[keycloak-seeder_0abd99d1-d]: at Volo.Abp.Data.DataSeeder.SeedAsync(DataSeedContext context)
[keycloak-seeder_0abd99d1-d]: at Castle.DynamicProxy.AsyncInterceptorBase.ProceedAsynchronous(IInvocation invocation, IInvocationProceedInfo proceedInfo)
[keycloak-seeder_0abd99d1-d]: at Volo.Abp.Castle.DynamicProxy.CastleAbpMethodInvocationAdapter.ProceedAsync()
[keycloak-seeder_0abd99d1-d]: at Volo.Abp.Uow.UnitOfWorkInterceptor.InterceptAsync(IAbpMethodInvocation invocation)
[keycloak-seeder_0abd99d1-d]: at Volo.Abp.Castle.DynamicProxy.CastleAsyncAbpInterceptorAdapter`1.InterceptAsync(IInvocation invocation, IInvocationProceedInfo proceedInfo, Func`3 proceed)
[keycloak-seeder_0abd99d1-d]: at EShopOnAbp.DbMigrator.MigrationService.MigrateAsync(CancellationToken cancellationToken) in C:\Users\kerim\source\repos\abp\eShopOnAbp\shared\EShopOnAbp.Keycloak.DbMigrator\MigrationService.cs:line 25
[keycloak-seeder_0abd99d1-d]: at EShopOnAbp.DbMigrator.DbMigratorHostedService.StartAsync(CancellationToken cancellationToken) in C:\Users\kerim\source\repos\abp\eShopOnAbp\shared\EShopOnAbp.Keycloak.DbMigrator\DbMigratorHostedService.cs:line 35
[keycloak-seeder_0abd99d1-d]: at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>b__15_1(IHostedService service, CancellationToken token)
[keycloak-seeder_0abd99d1-d]: at Microsoft.Extensions.Hosting.Internal.Host.ForeachService[T](IEnumerable`1 services, CancellationToken token, Boolean concurrent, Boolean abortOnFirstException, List`1 exceptions, Func`3 operation)
[keycloak-seeder_0abd99d1-d]: at Microsoft.Extensions.Hosting.Internal.Host.<StartAsync>g__LogAndRethrow|15_3(<>c__DisplayClass15_0&)
[keycloak-seeder_0abd99d1-d]: at Microsoft.Extensions.Hosting.Internal.Host.StartAsync(CancellationToken cancellationToken)
[keycloak-seeder_0abd99d1-d]: at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[keycloak-seeder_0abd99d1-d]: at Microsoft.Extensions.Hosting.HostingAbstractionsHostExtensions.RunAsync(IHost host, CancellationToken token)
[keycloak-seeder_0abd99d1-d]: at Program.Main(String[] args) in C:\Users\kerim\source\repos\abp\eShopOnAbp\shared\EShopOnAbp.Keycloak.DbMigrator\Program.cs:line 27
[keycloak-seeder_0abd99d1-d]: at Program.<Main>(String[] args)

**Comment by 15768495614** [comment]
重新运行

**Comment by thangitk14** [comment]
I have the same problem
