### ISSUE TITLE
After running run-tye.ps1, I encountered several problems

### ISSUE THREAD

**Issue by 15768495614** [abpframework/eShopOnAbp#260]
1、the web-public-gateway service show 
Fetch error
Failed to fetch http://administrationService/swagger/v1/swagger.json
Fetch error
Possible mixed-content issue? The page was loaded over https:// but a http:// URL was specified. Check that you are not attempting to load mixed content.

2、the public-web service  log show 
System.Threading.Tasks.TaskCanceledException: A task was canceled.

[public-web_83d057e2-6]: [18:32:52 INF] Sending HTTP request GET http://webpublicgateway/api/abp/application-configuration?IncludeLocalizationResources=False&api-version=1.0
[public-web_83d057e2-6]: [18:32:57 ERR] Resilience event occurred. EventName: 'OnTimeout', Source: '-standard//Standard-AttemptTimeout', Operation Key: 'null', Result: 'null'
[public-web_83d057e2-6]: [18:32:57 WRN] Execution attempt. Source: '-standard//Standard-Retry', Operation Key: 'null', Result: 'The operation didn't complete within the allowed timeout of '00:00:10'.', Handled: 'True', Attempt: '0', Execution Time: '10029.0442'
[public-web_83d057e2-6]: Polly.Timeout.TimeoutRejectedException: The operation didn't complete within the allowed timeout of '00:00:10'.
[public-web_83d057e2-6]: ---> System.Threading.Tasks.TaskCanceledException: A task was canceled.
[public-web_83d057e2-6]: at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context, CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates, ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount, IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean continueOnCapturedContext)
[public-web_83d057e2-6]: at Polly.AsyncPolicy`1.ExecuteAsync(Func`3 action, Context context, CancellationToken cancellationToken, Boolean continueOnCapturedContext)
[public-web_83d057e2-6]: at Microsoft.Extensions.Http.PolicyHttpMessageHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
[public-web_83d057e2-6]: at Microsoft.Extensions.ServiceDiscovery.Http.ResolvingHttpDelegatingHandler.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken) in /_/src/Microsoft.Extensions.ServiceDiscovery/Http/ResolvingHttpDelegatingHandler.cs:line 53
[public-web_83d057e2-6]: at Microsoft.Extensions.Http.Resilience.ResilienceHandler.<>c.<<SendAsync>b__3_0>d.MoveNext()
[public-web_83d057e2-6]: --- End of inner exception stack trace ---
[public-web_83d057e2-6]: at Polly.Utils.ExceptionUtilities.TrySetStackTrace[T](T exception)
[public-web_83d057e2-6]: at Polly.Timeout.TimeoutResilienceStrategy.ExecuteCore[TResult,TState](Func`3 callback, ResilienceContext context, TState state)
[public-web_83d057e2-6]: at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[public-web_83d057e2-6]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[public-web_83d057e2-6]: at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[public-web_83d057e2-6]: at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[public-web_83d057e2-6]: at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
[public-web_83d057e2-6]: at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
[public-web_83d057e2-6]: at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)
[public-web_83d057e2-6]: at System.Threading.Tasks.Task`1.TrySetResult(TResult result)
[public-web_83d057e2-6]: at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.SetExistingTaskResult(Task`1 task, TResult result)
[public-web_83d057e2-6]: at System.Runtime.CompilerServices.AsyncValueTaskMethodBuilder`1.SetResult(TResult result)
[public-web_83d057e2-6]: at Polly.Utils.StrategyHelper.<ExecuteCallbackSafeAsync>g__AwaitTask|0_0[TResult,TState,T](ValueTask`1 task, Boolean continueOnCapturedContext)
[public-web_83d057e2-6]: at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.ExecutionContextCallback(Object s)
[public-web_83d057e2-6]: at System.Threading.ExecutionContext.RunInternal(ExecutionContext executionContext, ContextCallback callback, Object state)
[public-web_83d057e2-6]: at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext(Thread threadPoolThread)
[public-web_83d057e2-6]: at System.Runtime.CompilerServices.AsyncTaskMethodBuilder`1.AsyncStateMachineBox`1.MoveNext()
[public-web_83d057e2-6]: at System.Runtime.CompilerServices.TaskAwaiter.<>c.<OutputWaitEtwEvents>b__12_0(Action innerContinuation, Task innerTask)
[public-web_83d057e2-6]: at System.Threading.Tasks.AwaitTaskContinuation.RunOrScheduleAction(Action action, Boolean allowInlining)
[public-web_83d057e2-6]: at System.Threading.Tasks.Task.RunContinuations(Object continuationObject)

3、In addition, do I need to do some additional processing for these links http://webpublicgateway? Can it be used normally?

**Comment by lee-vic** [comment]
I have the same problem but don't know how to solve it.

**Comment by lee-vic** [comment]
Modify the hosts file?
